### ISSUE TITLE
DuskTestCase.php not found

### ISSUE THREAD

**Issue by meysammahfouzi** [pikanji/oc-dusktests-plugin#1]
Hi and thanks for trying to bring dusk to OctoberCMS!
I think there should be some file called DuskTestCase.php in the tests directory for the plugin to work. At the moment when I run `composer update` I get this error:

>  [RuntimeException]
  Could not scan for classes inside "plugins/pikanji/dusktests/../../../tests/DuskTestCase.php" which does not appear to be a file nor a folder

Could you please provide the missing file?
Thanks 🙂

**Comment by meysammahfouzi** [comment]
I figured out that I have to manually install laravel/dusk first. I followed the steps below:

1. run `composer require laravel/dusk`
2. add `Laravel\Dusk\DuskServiceProvider::class` to the list of service providers in `config/app.php`
3. run `php artisan` to make sure `dusk` command has become available now
4. run `php artisan dusk:install` to generate `DuskTestCase.php` and other required files in tests directory
5. add `"pikanji/dusktests-plugin": "dev-master"` to the `require-dev` section of composer.json
6. run `composer update`
7. run `php artisan dusk` to run the example test found in `tests/Browser/ExampleTest.php`

tada!

**Comment by pikanji** [comment]
@meysammahfouzi Thanks for finding this issue! I confirmed the problem, and committed fixes. It should be ok now.

DuskTestCase.php is a file that will be installed by the command `php artisan dusk:install`. This step was missing in the README.

**Comment by pikanji** [comment]
@meysammahfouzi I just saw your new message after I posted my previous message. It seems you found out. If you do that manually, then actually you don't need this plugin, haha.

**Comment by meysammahfouzi** [comment]
@pikanji Ummm, without your plugin installed, running `php artisan dusk` gives this error:

> PHP Fatal error:  Class 'Tests\DuskTestCase' not found in /path/to/project/tests/Browser/ExampleTest.php on line 9

And after manually adding the following lines to `composer.json`:
```
"autoload-dev": {
    "classmap": [
        "tests/DuskTestCase.php"
    ]
},
```
and updating via `composer dump-autoload`, I get the following error after running `php artisan dusk`:

> PHP Fatal error:  Trait 'Tests\CreatesApplication' not found in /path/to/project/tests/DuskTestCase.php on line 12

But with your plugin installed, I get non of these errors :smile:

**Comment by meysammahfouzi** [comment]
So I think if you add `laravel/dusk` as a dependency to your project so that it gets installed automatically, everything will be fine.

**Comment by pikanji** [comment]
@meysammahfouzi Adding `laravel/dusk` as a dependency is not enough. You need to run `php artisan dusk:install`.

Without my plugin, I guess you need below in the composer.json of your project. This lines tell your project where the installed class files are.
```
    "autoload": {
        "classmap": [
            "tests/CreatesApplication.php",
            "tests/DuskTestCase.php"
        ]
    }
```

**Comment by meysammahfouzi** [comment]
@pikanji But running `php artisan dusk:install` does not generate the `tests/CreatesApplication.php` file.

**Comment by pikanji** [comment]
@meysammahfouzi Ah, sorry, that's right. I forgot that part. Another step you need is to add [tests/CreatesApplication.php](https://github.com/laravel/laravel/blob/develop/tests/CreatesApplication.php) to tests directory of your project. In Laravel project, it is included in bear project, but not in OctoberCMS project.

**Comment by meysammahfouzi** [comment]
@pikanji So I guess it's beginning to make some sense to install your plugin :wink: Not many people may want to manually copy the missing files or update their `composer.json`. I think the whole point of the plugin is to make those tasks automatic. Right? If you add `laravel/dusk` as a dependency so that it automatically gets installed, the only thing that remains is to run `php artisan dusk:install` to get everything working.

**Comment by pikanji** [comment]
@meysammahfouzi Yeah, I tried to automate as much as possible. If you add `pikanji/dusktests-plugin` to your composer.json, then you just need to execute `composer update` and then `php artisan dusk:install`. `laravel/dusk` dependency is already defined in `pikanji/dusktests-plugin`, so you don't need to add by yourself.

**Comment by meysammahfouzi** [comment]
You are right, I didn't notice that `laravel/dusk` has already been added as dependency. So the only thing needed is running the following two commands:

1. composer require --dev pikanji/dusktests-plugin
2. php artisan dusk:install

**Comment by pikanji** [comment]
@meysammahfouzi Yes, exactly! I'm glad that you found some value in my plugin.
You helped me to fix a bug. Thanks so much!

**Comment by meysammahfouzi** [comment]
@pikanji Yea I had almost given up running a simple test with dusk on October because of the lack of enough documentation. Your plugin was a huge help for me, thanks! The only thing that remains is tackling unit testing of APIs defined in `routes.php` file of plugins which is still problematic in October.

**Comment by pikanji** [comment]
@meysammahfouzi Humm, I don't have information about that one, yet...
BTW, Thanks for your PR! I merged it!
